version: '3'
services:
    app:
        container_name: betting-site-backend-1
        restart: always
        build: .
        ports:
            - '1998:1998'
        links:
            - db
    db:
        container_name: betting-site-db-1
        image: mongo
        ports:
            - '27017:27017'
